// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LearningEnvironmentMonitor.proto

package com.eLearningSystem.grpc;

public final class LearningEnvironmentMonitorOuterClass {
  private LearningEnvironmentMonitorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RoomConditionsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RoomConditionsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string location = 1;</code>
     */
    java.lang.String getLocation();
    /**
     * <code>string location = 1;</code>
     */
    com.google.protobuf.ByteString
        getLocationBytes();
  }
  /**
   * Protobuf type {@code RoomConditionsRequest}
   */
  public  static final class RoomConditionsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RoomConditionsRequest)
      RoomConditionsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomConditionsRequest.newBuilder() to construct.
    private RoomConditionsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomConditionsRequest() {
      location_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoomConditionsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              location_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_RoomConditionsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_RoomConditionsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest.class, com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest.Builder.class);
    }

    public static final int LOCATION_FIELD_NUMBER = 1;
    private volatile java.lang.Object location_;
    /**
     * <code>string location = 1;</code>
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      }
    }
    /**
     * <code>string location = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLocationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, location_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLocationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, location_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest)) {
        return super.equals(obj);
      }
      com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest other = (com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest) obj;

      boolean result = true;
      result = result && getLocation()
          .equals(other.getLocation());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RoomConditionsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RoomConditionsRequest)
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_RoomConditionsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_RoomConditionsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest.class, com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest.Builder.class);
      }

      // Construct using com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        location_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_RoomConditionsRequest_descriptor;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest getDefaultInstanceForType() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest build() {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest buildPartial() {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest result = new com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest(this);
        result.location_ = location_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest) {
          return mergeFrom((com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest other) {
        if (other == com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest.getDefaultInstance()) return this;
        if (!other.getLocation().isEmpty()) {
          location_ = other.location_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object location_ = "";
      /**
       * <code>string location = 1;</code>
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string location = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string location = 1;</code>
       */
      public Builder setLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string location = 1;</code>
       */
      public Builder clearLocation() {
        
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      /**
       * <code>string location = 1;</code>
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        location_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RoomConditionsRequest)
    }

    // @@protoc_insertion_point(class_scope:RoomConditionsRequest)
    private static final com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest();
    }

    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomConditionsRequest>
        PARSER = new com.google.protobuf.AbstractParser<RoomConditionsRequest>() {
      @java.lang.Override
      public RoomConditionsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomConditionsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoomConditionsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoomConditionsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RoomConditionsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RoomConditionsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float temperature = 1;</code>
     */
    float getTemperature();

    /**
     * <code>float humidity = 2;</code>
     */
    float getHumidity();

    /**
     * <code>float co2Level = 3;</code>
     */
    float getCo2Level();

    /**
     * <code>float airQuality = 4;</code>
     */
    float getAirQuality();
  }
  /**
   * Protobuf type {@code RoomConditionsResponse}
   */
  public  static final class RoomConditionsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RoomConditionsResponse)
      RoomConditionsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RoomConditionsResponse.newBuilder() to construct.
    private RoomConditionsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RoomConditionsResponse() {
      temperature_ = 0F;
      humidity_ = 0F;
      co2Level_ = 0F;
      airQuality_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RoomConditionsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              temperature_ = input.readFloat();
              break;
            }
            case 21: {

              humidity_ = input.readFloat();
              break;
            }
            case 29: {

              co2Level_ = input.readFloat();
              break;
            }
            case 37: {

              airQuality_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_RoomConditionsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_RoomConditionsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse.class, com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse.Builder.class);
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 1;
    private float temperature_;
    /**
     * <code>float temperature = 1;</code>
     */
    public float getTemperature() {
      return temperature_;
    }

    public static final int HUMIDITY_FIELD_NUMBER = 2;
    private float humidity_;
    /**
     * <code>float humidity = 2;</code>
     */
    public float getHumidity() {
      return humidity_;
    }

    public static final int CO2LEVEL_FIELD_NUMBER = 3;
    private float co2Level_;
    /**
     * <code>float co2Level = 3;</code>
     */
    public float getCo2Level() {
      return co2Level_;
    }

    public static final int AIRQUALITY_FIELD_NUMBER = 4;
    private float airQuality_;
    /**
     * <code>float airQuality = 4;</code>
     */
    public float getAirQuality() {
      return airQuality_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (temperature_ != 0F) {
        output.writeFloat(1, temperature_);
      }
      if (humidity_ != 0F) {
        output.writeFloat(2, humidity_);
      }
      if (co2Level_ != 0F) {
        output.writeFloat(3, co2Level_);
      }
      if (airQuality_ != 0F) {
        output.writeFloat(4, airQuality_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (temperature_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, temperature_);
      }
      if (humidity_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, humidity_);
      }
      if (co2Level_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, co2Level_);
      }
      if (airQuality_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, airQuality_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse)) {
        return super.equals(obj);
      }
      com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse other = (com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getTemperature())
          == java.lang.Float.floatToIntBits(
              other.getTemperature()));
      result = result && (
          java.lang.Float.floatToIntBits(getHumidity())
          == java.lang.Float.floatToIntBits(
              other.getHumidity()));
      result = result && (
          java.lang.Float.floatToIntBits(getCo2Level())
          == java.lang.Float.floatToIntBits(
              other.getCo2Level()));
      result = result && (
          java.lang.Float.floatToIntBits(getAirQuality())
          == java.lang.Float.floatToIntBits(
              other.getAirQuality()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTemperature());
      hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHumidity());
      hash = (37 * hash) + CO2LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCo2Level());
      hash = (37 * hash) + AIRQUALITY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAirQuality());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RoomConditionsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RoomConditionsResponse)
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_RoomConditionsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_RoomConditionsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse.class, com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse.Builder.class);
      }

      // Construct using com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        temperature_ = 0F;

        humidity_ = 0F;

        co2Level_ = 0F;

        airQuality_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_RoomConditionsResponse_descriptor;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse getDefaultInstanceForType() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse build() {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse buildPartial() {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse result = new com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse(this);
        result.temperature_ = temperature_;
        result.humidity_ = humidity_;
        result.co2Level_ = co2Level_;
        result.airQuality_ = airQuality_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse) {
          return mergeFrom((com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse other) {
        if (other == com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse.getDefaultInstance()) return this;
        if (other.getTemperature() != 0F) {
          setTemperature(other.getTemperature());
        }
        if (other.getHumidity() != 0F) {
          setHumidity(other.getHumidity());
        }
        if (other.getCo2Level() != 0F) {
          setCo2Level(other.getCo2Level());
        }
        if (other.getAirQuality() != 0F) {
          setAirQuality(other.getAirQuality());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float temperature_ ;
      /**
       * <code>float temperature = 1;</code>
       */
      public float getTemperature() {
        return temperature_;
      }
      /**
       * <code>float temperature = 1;</code>
       */
      public Builder setTemperature(float value) {
        
        temperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float temperature = 1;</code>
       */
      public Builder clearTemperature() {
        
        temperature_ = 0F;
        onChanged();
        return this;
      }

      private float humidity_ ;
      /**
       * <code>float humidity = 2;</code>
       */
      public float getHumidity() {
        return humidity_;
      }
      /**
       * <code>float humidity = 2;</code>
       */
      public Builder setHumidity(float value) {
        
        humidity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float humidity = 2;</code>
       */
      public Builder clearHumidity() {
        
        humidity_ = 0F;
        onChanged();
        return this;
      }

      private float co2Level_ ;
      /**
       * <code>float co2Level = 3;</code>
       */
      public float getCo2Level() {
        return co2Level_;
      }
      /**
       * <code>float co2Level = 3;</code>
       */
      public Builder setCo2Level(float value) {
        
        co2Level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float co2Level = 3;</code>
       */
      public Builder clearCo2Level() {
        
        co2Level_ = 0F;
        onChanged();
        return this;
      }

      private float airQuality_ ;
      /**
       * <code>float airQuality = 4;</code>
       */
      public float getAirQuality() {
        return airQuality_;
      }
      /**
       * <code>float airQuality = 4;</code>
       */
      public Builder setAirQuality(float value) {
        
        airQuality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float airQuality = 4;</code>
       */
      public Builder clearAirQuality() {
        
        airQuality_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RoomConditionsResponse)
    }

    // @@protoc_insertion_point(class_scope:RoomConditionsResponse)
    private static final com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse();
    }

    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RoomConditionsResponse>
        PARSER = new com.google.protobuf.AbstractParser<RoomConditionsResponse>() {
      @java.lang.Override
      public RoomConditionsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RoomConditionsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RoomConditionsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RoomConditionsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.RoomConditionsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ThresholdRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ThresholdRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string location = 1;</code>
     */
    java.lang.String getLocation();
    /**
     * <code>string location = 1;</code>
     */
    com.google.protobuf.ByteString
        getLocationBytes();

    /**
     * <code>float temperatureMin = 2;</code>
     */
    float getTemperatureMin();

    /**
     * <code>float humidityMax = 3;</code>
     */
    float getHumidityMax();

    /**
     * <code>float co2Threshold = 4;</code>
     */
    float getCo2Threshold();
  }
  /**
   * Protobuf type {@code ThresholdRequest}
   */
  public  static final class ThresholdRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ThresholdRequest)
      ThresholdRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ThresholdRequest.newBuilder() to construct.
    private ThresholdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ThresholdRequest() {
      location_ = "";
      temperatureMin_ = 0F;
      humidityMax_ = 0F;
      co2Threshold_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ThresholdRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              location_ = s;
              break;
            }
            case 21: {

              temperatureMin_ = input.readFloat();
              break;
            }
            case 29: {

              humidityMax_ = input.readFloat();
              break;
            }
            case 37: {

              co2Threshold_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_ThresholdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_ThresholdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest.class, com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest.Builder.class);
    }

    public static final int LOCATION_FIELD_NUMBER = 1;
    private volatile java.lang.Object location_;
    /**
     * <code>string location = 1;</code>
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      }
    }
    /**
     * <code>string location = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMPERATUREMIN_FIELD_NUMBER = 2;
    private float temperatureMin_;
    /**
     * <code>float temperatureMin = 2;</code>
     */
    public float getTemperatureMin() {
      return temperatureMin_;
    }

    public static final int HUMIDITYMAX_FIELD_NUMBER = 3;
    private float humidityMax_;
    /**
     * <code>float humidityMax = 3;</code>
     */
    public float getHumidityMax() {
      return humidityMax_;
    }

    public static final int CO2THRESHOLD_FIELD_NUMBER = 4;
    private float co2Threshold_;
    /**
     * <code>float co2Threshold = 4;</code>
     */
    public float getCo2Threshold() {
      return co2Threshold_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLocationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, location_);
      }
      if (temperatureMin_ != 0F) {
        output.writeFloat(2, temperatureMin_);
      }
      if (humidityMax_ != 0F) {
        output.writeFloat(3, humidityMax_);
      }
      if (co2Threshold_ != 0F) {
        output.writeFloat(4, co2Threshold_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLocationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, location_);
      }
      if (temperatureMin_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, temperatureMin_);
      }
      if (humidityMax_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, humidityMax_);
      }
      if (co2Threshold_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, co2Threshold_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest)) {
        return super.equals(obj);
      }
      com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest other = (com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest) obj;

      boolean result = true;
      result = result && getLocation()
          .equals(other.getLocation());
      result = result && (
          java.lang.Float.floatToIntBits(getTemperatureMin())
          == java.lang.Float.floatToIntBits(
              other.getTemperatureMin()));
      result = result && (
          java.lang.Float.floatToIntBits(getHumidityMax())
          == java.lang.Float.floatToIntBits(
              other.getHumidityMax()));
      result = result && (
          java.lang.Float.floatToIntBits(getCo2Threshold())
          == java.lang.Float.floatToIntBits(
              other.getCo2Threshold()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
      hash = (37 * hash) + TEMPERATUREMIN_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTemperatureMin());
      hash = (37 * hash) + HUMIDITYMAX_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getHumidityMax());
      hash = (37 * hash) + CO2THRESHOLD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getCo2Threshold());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ThresholdRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ThresholdRequest)
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_ThresholdRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_ThresholdRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest.class, com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest.Builder.class);
      }

      // Construct using com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        location_ = "";

        temperatureMin_ = 0F;

        humidityMax_ = 0F;

        co2Threshold_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_ThresholdRequest_descriptor;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest getDefaultInstanceForType() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest build() {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest buildPartial() {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest result = new com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest(this);
        result.location_ = location_;
        result.temperatureMin_ = temperatureMin_;
        result.humidityMax_ = humidityMax_;
        result.co2Threshold_ = co2Threshold_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest) {
          return mergeFrom((com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest other) {
        if (other == com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest.getDefaultInstance()) return this;
        if (!other.getLocation().isEmpty()) {
          location_ = other.location_;
          onChanged();
        }
        if (other.getTemperatureMin() != 0F) {
          setTemperatureMin(other.getTemperatureMin());
        }
        if (other.getHumidityMax() != 0F) {
          setHumidityMax(other.getHumidityMax());
        }
        if (other.getCo2Threshold() != 0F) {
          setCo2Threshold(other.getCo2Threshold());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object location_ = "";
      /**
       * <code>string location = 1;</code>
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string location = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string location = 1;</code>
       */
      public Builder setLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string location = 1;</code>
       */
      public Builder clearLocation() {
        
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      /**
       * <code>string location = 1;</code>
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        location_ = value;
        onChanged();
        return this;
      }

      private float temperatureMin_ ;
      /**
       * <code>float temperatureMin = 2;</code>
       */
      public float getTemperatureMin() {
        return temperatureMin_;
      }
      /**
       * <code>float temperatureMin = 2;</code>
       */
      public Builder setTemperatureMin(float value) {
        
        temperatureMin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float temperatureMin = 2;</code>
       */
      public Builder clearTemperatureMin() {
        
        temperatureMin_ = 0F;
        onChanged();
        return this;
      }

      private float humidityMax_ ;
      /**
       * <code>float humidityMax = 3;</code>
       */
      public float getHumidityMax() {
        return humidityMax_;
      }
      /**
       * <code>float humidityMax = 3;</code>
       */
      public Builder setHumidityMax(float value) {
        
        humidityMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float humidityMax = 3;</code>
       */
      public Builder clearHumidityMax() {
        
        humidityMax_ = 0F;
        onChanged();
        return this;
      }

      private float co2Threshold_ ;
      /**
       * <code>float co2Threshold = 4;</code>
       */
      public float getCo2Threshold() {
        return co2Threshold_;
      }
      /**
       * <code>float co2Threshold = 4;</code>
       */
      public Builder setCo2Threshold(float value) {
        
        co2Threshold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float co2Threshold = 4;</code>
       */
      public Builder clearCo2Threshold() {
        
        co2Threshold_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ThresholdRequest)
    }

    // @@protoc_insertion_point(class_scope:ThresholdRequest)
    private static final com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest();
    }

    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ThresholdRequest>
        PARSER = new com.google.protobuf.AbstractParser<ThresholdRequest>() {
      @java.lang.Override
      public ThresholdRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ThresholdRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ThresholdRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ThresholdRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ThresholdResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ThresholdResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code ThresholdResponse}
   */
  public  static final class ThresholdResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ThresholdResponse)
      ThresholdResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ThresholdResponse.newBuilder() to construct.
    private ThresholdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ThresholdResponse() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ThresholdResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_ThresholdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_ThresholdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse.class, com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse)) {
        return super.equals(obj);
      }
      com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse other = (com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse) obj;

      boolean result = true;
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ThresholdResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ThresholdResponse)
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_ThresholdResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_ThresholdResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse.class, com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse.Builder.class);
      }

      // Construct using com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.internal_static_ThresholdResponse_descriptor;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse getDefaultInstanceForType() {
        return com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse build() {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse buildPartial() {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse result = new com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse) {
          return mergeFrom((com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse other) {
        if (other == com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ThresholdResponse)
    }

    // @@protoc_insertion_point(class_scope:ThresholdResponse)
    private static final com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse();
    }

    public static com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ThresholdResponse>
        PARSER = new com.google.protobuf.AbstractParser<ThresholdResponse>() {
      @java.lang.Override
      public ThresholdResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ThresholdResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ThresholdResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ThresholdResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.eLearningSystem.grpc.LearningEnvironmentMonitorOuterClass.ThresholdResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomConditionsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomConditionsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomConditionsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomConditionsResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ThresholdRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ThresholdRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ThresholdResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ThresholdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n LearningEnvironmentMonitor.proto\")\n\025Ro" +
      "omConditionsRequest\022\020\n\010location\030\001 \001(\t\"e\n" +
      "\026RoomConditionsResponse\022\023\n\013temperature\030\001" +
      " \001(\002\022\020\n\010humidity\030\002 \001(\002\022\020\n\010co2Level\030\003 \001(\002" +
      "\022\022\n\nairQuality\030\004 \001(\002\"g\n\020ThresholdRequest" +
      "\022\020\n\010location\030\001 \001(\t\022\026\n\016temperatureMin\030\002 \001" +
      "(\002\022\023\n\013humidityMax\030\003 \001(\002\022\024\n\014co2Threshold\030" +
      "\004 \001(\002\"$\n\021ThresholdResponse\022\017\n\007message\030\001 " +
      "\001(\t2\232\001\n\032LearningEnvironmentMonitor\022D\n\021Ge" +
      "tRoomConditions\022\026.RoomConditionsRequest\032" +
      "\027.RoomConditionsResponse\0226\n\rSetThreshold" +
      "s\022\021.ThresholdRequest\032\022.ThresholdResponse" +
      "B\032\n\030com.eLearningSystem.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RoomConditionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RoomConditionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomConditionsRequest_descriptor,
        new java.lang.String[] { "Location", });
    internal_static_RoomConditionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_RoomConditionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomConditionsResponse_descriptor,
        new java.lang.String[] { "Temperature", "Humidity", "Co2Level", "AirQuality", });
    internal_static_ThresholdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ThresholdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ThresholdRequest_descriptor,
        new java.lang.String[] { "Location", "TemperatureMin", "HumidityMax", "Co2Threshold", });
    internal_static_ThresholdResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ThresholdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ThresholdResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
