// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartAttendanceMonitor.proto

package com.eLearningSystem.grpc;

public final class SmartAttendanceMonitorOuterClass {
  private SmartAttendanceMonitorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AttendanceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AttendanceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string studentId = 1;</code>
     */
    java.lang.String getStudentId();
    /**
     * <code>string studentId = 1;</code>
     */
    com.google.protobuf.ByteString
        getStudentIdBytes();

    /**
     * <code>string timeStamp = 2;</code>
     */
    java.lang.String getTimeStamp();
    /**
     * <code>string timeStamp = 2;</code>
     */
    com.google.protobuf.ByteString
        getTimeStampBytes();

    /**
     * <code>string location = 3;</code>
     */
    java.lang.String getLocation();
    /**
     * <code>string location = 3;</code>
     */
    com.google.protobuf.ByteString
        getLocationBytes();
  }
  /**
   * Protobuf type {@code AttendanceRequest}
   */
  public  static final class AttendanceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AttendanceRequest)
      AttendanceRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AttendanceRequest.newBuilder() to construct.
    private AttendanceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AttendanceRequest() {
      studentId_ = "";
      timeStamp_ = "";
      location_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AttendanceRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              studentId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              timeStamp_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              location_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_AttendanceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_AttendanceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest.class, com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest.Builder.class);
    }

    public static final int STUDENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object studentId_;
    /**
     * <code>string studentId = 1;</code>
     */
    public java.lang.String getStudentId() {
      java.lang.Object ref = studentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studentId_ = s;
        return s;
      }
    }
    /**
     * <code>string studentId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStudentIdBytes() {
      java.lang.Object ref = studentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private volatile java.lang.Object timeStamp_;
    /**
     * <code>string timeStamp = 2;</code>
     */
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeStamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timeStamp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_FIELD_NUMBER = 3;
    private volatile java.lang.Object location_;
    /**
     * <code>string location = 3;</code>
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      }
    }
    /**
     * <code>string location = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStudentIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, studentId_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, timeStamp_);
      }
      if (!getLocationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, location_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStudentIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, studentId_);
      }
      if (!getTimeStampBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, timeStamp_);
      }
      if (!getLocationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, location_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest)) {
        return super.equals(obj);
      }
      com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest other = (com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest) obj;

      boolean result = true;
      result = result && getStudentId()
          .equals(other.getStudentId());
      result = result && getTimeStamp()
          .equals(other.getTimeStamp());
      result = result && getLocation()
          .equals(other.getLocation());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STUDENTID_FIELD_NUMBER;
      hash = (53 * hash) + getStudentId().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimeStamp().hashCode();
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AttendanceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AttendanceRequest)
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_AttendanceRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_AttendanceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest.class, com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest.Builder.class);
      }

      // Construct using com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        studentId_ = "";

        timeStamp_ = "";

        location_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_AttendanceRequest_descriptor;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest getDefaultInstanceForType() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest build() {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest buildPartial() {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest result = new com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest(this);
        result.studentId_ = studentId_;
        result.timeStamp_ = timeStamp_;
        result.location_ = location_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest) {
          return mergeFrom((com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest other) {
        if (other == com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest.getDefaultInstance()) return this;
        if (!other.getStudentId().isEmpty()) {
          studentId_ = other.studentId_;
          onChanged();
        }
        if (!other.getTimeStamp().isEmpty()) {
          timeStamp_ = other.timeStamp_;
          onChanged();
        }
        if (!other.getLocation().isEmpty()) {
          location_ = other.location_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object studentId_ = "";
      /**
       * <code>string studentId = 1;</code>
       */
      public java.lang.String getStudentId() {
        java.lang.Object ref = studentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          studentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string studentId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStudentIdBytes() {
        java.lang.Object ref = studentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          studentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string studentId = 1;</code>
       */
      public Builder setStudentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        studentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string studentId = 1;</code>
       */
      public Builder clearStudentId() {
        
        studentId_ = getDefaultInstance().getStudentId();
        onChanged();
        return this;
      }
      /**
       * <code>string studentId = 1;</code>
       */
      public Builder setStudentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        studentId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object timeStamp_ = "";
      /**
       * <code>string timeStamp = 2;</code>
       */
      public java.lang.String getTimeStamp() {
        java.lang.Object ref = timeStamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timeStamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timeStamp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTimeStampBytes() {
        java.lang.Object ref = timeStamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timeStamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timeStamp = 2;</code>
       */
      public Builder setTimeStamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string timeStamp = 2;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = getDefaultInstance().getTimeStamp();
        onChanged();
        return this;
      }
      /**
       * <code>string timeStamp = 2;</code>
       */
      public Builder setTimeStampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        timeStamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object location_ = "";
      /**
       * <code>string location = 3;</code>
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string location = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string location = 3;</code>
       */
      public Builder setLocation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        location_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string location = 3;</code>
       */
      public Builder clearLocation() {
        
        location_ = getDefaultInstance().getLocation();
        onChanged();
        return this;
      }
      /**
       * <code>string location = 3;</code>
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        location_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AttendanceRequest)
    }

    // @@protoc_insertion_point(class_scope:AttendanceRequest)
    private static final com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest();
    }

    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AttendanceRequest>
        PARSER = new com.google.protobuf.AbstractParser<AttendanceRequest>() {
      @java.lang.Override
      public AttendanceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AttendanceRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AttendanceRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AttendanceRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AttendanceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AttendanceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string status = 1;</code>
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 1;</code>
     */
    com.google.protobuf.ByteString
        getStatusBytes();
  }
  /**
   * Protobuf type {@code AttendanceResponse}
   */
  public  static final class AttendanceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AttendanceResponse)
      AttendanceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AttendanceResponse.newBuilder() to construct.
    private AttendanceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AttendanceResponse() {
      status_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AttendanceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_AttendanceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_AttendanceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse.class, com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 1;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse)) {
        return super.equals(obj);
      }
      com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse other = (com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse) obj;

      boolean result = true;
      result = result && getStatus()
          .equals(other.getStatus());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AttendanceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AttendanceResponse)
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_AttendanceResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_AttendanceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse.class, com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse.Builder.class);
      }

      // Construct using com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_AttendanceResponse_descriptor;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse getDefaultInstanceForType() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse build() {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse buildPartial() {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse result = new com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse(this);
        result.status_ = status_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse) {
          return mergeFrom((com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse other) {
        if (other == com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse.getDefaultInstance()) return this;
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 1;</code>
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 1;</code>
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 1;</code>
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        status_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AttendanceResponse)
    }

    // @@protoc_insertion_point(class_scope:AttendanceResponse)
    private static final com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse();
    }

    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AttendanceResponse>
        PARSER = new com.google.protobuf.AbstractParser<AttendanceResponse>() {
      @java.lang.Override
      public AttendanceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AttendanceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AttendanceResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AttendanceResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.AttendanceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SummaryRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SummaryRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string studentId = 1;</code>
     */
    java.lang.String getStudentId();
    /**
     * <code>string studentId = 1;</code>
     */
    com.google.protobuf.ByteString
        getStudentIdBytes();
  }
  /**
   * Protobuf type {@code SummaryRequest}
   */
  public  static final class SummaryRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SummaryRequest)
      SummaryRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SummaryRequest.newBuilder() to construct.
    private SummaryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SummaryRequest() {
      studentId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SummaryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              studentId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_SummaryRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_SummaryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest.class, com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest.Builder.class);
    }

    public static final int STUDENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object studentId_;
    /**
     * <code>string studentId = 1;</code>
     */
    public java.lang.String getStudentId() {
      java.lang.Object ref = studentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studentId_ = s;
        return s;
      }
    }
    /**
     * <code>string studentId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStudentIdBytes() {
      java.lang.Object ref = studentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStudentIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, studentId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStudentIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, studentId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest)) {
        return super.equals(obj);
      }
      com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest other = (com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest) obj;

      boolean result = true;
      result = result && getStudentId()
          .equals(other.getStudentId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STUDENTID_FIELD_NUMBER;
      hash = (53 * hash) + getStudentId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SummaryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SummaryRequest)
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_SummaryRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_SummaryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest.class, com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest.Builder.class);
      }

      // Construct using com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        studentId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_SummaryRequest_descriptor;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest getDefaultInstanceForType() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest build() {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest buildPartial() {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest result = new com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest(this);
        result.studentId_ = studentId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest) {
          return mergeFrom((com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest other) {
        if (other == com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest.getDefaultInstance()) return this;
        if (!other.getStudentId().isEmpty()) {
          studentId_ = other.studentId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object studentId_ = "";
      /**
       * <code>string studentId = 1;</code>
       */
      public java.lang.String getStudentId() {
        java.lang.Object ref = studentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          studentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string studentId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStudentIdBytes() {
        java.lang.Object ref = studentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          studentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string studentId = 1;</code>
       */
      public Builder setStudentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        studentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string studentId = 1;</code>
       */
      public Builder clearStudentId() {
        
        studentId_ = getDefaultInstance().getStudentId();
        onChanged();
        return this;
      }
      /**
       * <code>string studentId = 1;</code>
       */
      public Builder setStudentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        studentId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SummaryRequest)
    }

    // @@protoc_insertion_point(class_scope:SummaryRequest)
    private static final com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest();
    }

    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SummaryRequest>
        PARSER = new com.google.protobuf.AbstractParser<SummaryRequest>() {
      @java.lang.Override
      public SummaryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SummaryRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SummaryRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SummaryRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SummaryResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SummaryResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sessionsTotal = 1;</code>
     */
    int getSessionsTotal();

    /**
     * <code>int32 sessionsAttended = 2;</code>
     */
    int getSessionsAttended();

    /**
     * <code>float attendanceRate = 3;</code>
     */
    float getAttendanceRate();
  }
  /**
   * Protobuf type {@code SummaryResponse}
   */
  public  static final class SummaryResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SummaryResponse)
      SummaryResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SummaryResponse.newBuilder() to construct.
    private SummaryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SummaryResponse() {
      sessionsTotal_ = 0;
      sessionsAttended_ = 0;
      attendanceRate_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SummaryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sessionsTotal_ = input.readInt32();
              break;
            }
            case 16: {

              sessionsAttended_ = input.readInt32();
              break;
            }
            case 29: {

              attendanceRate_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_SummaryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_SummaryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse.class, com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse.Builder.class);
    }

    public static final int SESSIONSTOTAL_FIELD_NUMBER = 1;
    private int sessionsTotal_;
    /**
     * <code>int32 sessionsTotal = 1;</code>
     */
    public int getSessionsTotal() {
      return sessionsTotal_;
    }

    public static final int SESSIONSATTENDED_FIELD_NUMBER = 2;
    private int sessionsAttended_;
    /**
     * <code>int32 sessionsAttended = 2;</code>
     */
    public int getSessionsAttended() {
      return sessionsAttended_;
    }

    public static final int ATTENDANCERATE_FIELD_NUMBER = 3;
    private float attendanceRate_;
    /**
     * <code>float attendanceRate = 3;</code>
     */
    public float getAttendanceRate() {
      return attendanceRate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sessionsTotal_ != 0) {
        output.writeInt32(1, sessionsTotal_);
      }
      if (sessionsAttended_ != 0) {
        output.writeInt32(2, sessionsAttended_);
      }
      if (attendanceRate_ != 0F) {
        output.writeFloat(3, attendanceRate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sessionsTotal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sessionsTotal_);
      }
      if (sessionsAttended_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sessionsAttended_);
      }
      if (attendanceRate_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, attendanceRate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse)) {
        return super.equals(obj);
      }
      com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse other = (com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse) obj;

      boolean result = true;
      result = result && (getSessionsTotal()
          == other.getSessionsTotal());
      result = result && (getSessionsAttended()
          == other.getSessionsAttended());
      result = result && (
          java.lang.Float.floatToIntBits(getAttendanceRate())
          == java.lang.Float.floatToIntBits(
              other.getAttendanceRate()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SESSIONSTOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getSessionsTotal();
      hash = (37 * hash) + SESSIONSATTENDED_FIELD_NUMBER;
      hash = (53 * hash) + getSessionsAttended();
      hash = (37 * hash) + ATTENDANCERATE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAttendanceRate());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SummaryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SummaryResponse)
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_SummaryResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_SummaryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse.class, com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse.Builder.class);
      }

      // Construct using com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sessionsTotal_ = 0;

        sessionsAttended_ = 0;

        attendanceRate_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.internal_static_SummaryResponse_descriptor;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse getDefaultInstanceForType() {
        return com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse build() {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse buildPartial() {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse result = new com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse(this);
        result.sessionsTotal_ = sessionsTotal_;
        result.sessionsAttended_ = sessionsAttended_;
        result.attendanceRate_ = attendanceRate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse) {
          return mergeFrom((com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse other) {
        if (other == com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse.getDefaultInstance()) return this;
        if (other.getSessionsTotal() != 0) {
          setSessionsTotal(other.getSessionsTotal());
        }
        if (other.getSessionsAttended() != 0) {
          setSessionsAttended(other.getSessionsAttended());
        }
        if (other.getAttendanceRate() != 0F) {
          setAttendanceRate(other.getAttendanceRate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sessionsTotal_ ;
      /**
       * <code>int32 sessionsTotal = 1;</code>
       */
      public int getSessionsTotal() {
        return sessionsTotal_;
      }
      /**
       * <code>int32 sessionsTotal = 1;</code>
       */
      public Builder setSessionsTotal(int value) {
        
        sessionsTotal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sessionsTotal = 1;</code>
       */
      public Builder clearSessionsTotal() {
        
        sessionsTotal_ = 0;
        onChanged();
        return this;
      }

      private int sessionsAttended_ ;
      /**
       * <code>int32 sessionsAttended = 2;</code>
       */
      public int getSessionsAttended() {
        return sessionsAttended_;
      }
      /**
       * <code>int32 sessionsAttended = 2;</code>
       */
      public Builder setSessionsAttended(int value) {
        
        sessionsAttended_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sessionsAttended = 2;</code>
       */
      public Builder clearSessionsAttended() {
        
        sessionsAttended_ = 0;
        onChanged();
        return this;
      }

      private float attendanceRate_ ;
      /**
       * <code>float attendanceRate = 3;</code>
       */
      public float getAttendanceRate() {
        return attendanceRate_;
      }
      /**
       * <code>float attendanceRate = 3;</code>
       */
      public Builder setAttendanceRate(float value) {
        
        attendanceRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float attendanceRate = 3;</code>
       */
      public Builder clearAttendanceRate() {
        
        attendanceRate_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SummaryResponse)
    }

    // @@protoc_insertion_point(class_scope:SummaryResponse)
    private static final com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse();
    }

    public static com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SummaryResponse>
        PARSER = new com.google.protobuf.AbstractParser<SummaryResponse>() {
      @java.lang.Override
      public SummaryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SummaryResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SummaryResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SummaryResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.eLearningSystem.grpc.SmartAttendanceMonitorOuterClass.SummaryResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AttendanceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AttendanceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AttendanceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AttendanceResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SummaryRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SummaryRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SummaryResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SummaryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034SmartAttendanceMonitor.proto\"K\n\021Attend" +
      "anceRequest\022\021\n\tstudentId\030\001 \001(\t\022\021\n\ttimeSt" +
      "amp\030\002 \001(\t\022\020\n\010location\030\003 \001(\t\"$\n\022Attendanc" +
      "eResponse\022\016\n\006status\030\001 \001(\t\"#\n\016SummaryRequ" +
      "est\022\021\n\tstudentId\030\001 \001(\t\"Z\n\017SummaryRespons" +
      "e\022\025\n\rsessionsTotal\030\001 \001(\005\022\030\n\020sessionsAtte" +
      "nded\030\002 \001(\005\022\026\n\016attendanceRate\030\003 \001(\0022\220\001\n\026S" +
      "martAttendanceMonitor\022;\n\020recordAttendanc" +
      "e\022\022.AttendanceRequest\032\023.AttendanceRespon" +
      "se\0229\n\024GetAttendanceSummary\022\017.SummaryRequ" +
      "est\032\020.SummaryResponseB\032\n\030com.eLearningSy" +
      "stem.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AttendanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AttendanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AttendanceRequest_descriptor,
        new java.lang.String[] { "StudentId", "TimeStamp", "Location", });
    internal_static_AttendanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AttendanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AttendanceResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_SummaryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SummaryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SummaryRequest_descriptor,
        new java.lang.String[] { "StudentId", });
    internal_static_SummaryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SummaryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SummaryResponse_descriptor,
        new java.lang.String[] { "SessionsTotal", "SessionsAttended", "AttendanceRate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
